name: CICD Lab 

on: [push]

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x ./script_1.sh
    - run: ./script_1.sh

  job2:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - run: chmod +x ./script_2.sh
    - run: ./script_2.sh
