name: CICD Lab 

on: [push]

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x /script_1

  script_2:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - run: ls
    - run: mkdir testDir
    - run: ls
    - run: mv cafe.yaml feature2.md hello.txt id.txt merge.txt testDir/
    - run: echo *
